package de.vorb.leptonica;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * <i>native declaration :
 * C:\Users\Paul\Studium\Masterarbeit\Entwicklung\VS2013\
 * tesseract-vs2013\liblept\include\pix.h:450</i><br>
 * This file was autogenerated by <a
 * href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a
 * href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few
 * opensource projects.</a>.<br>
 * For help, please visit <a
 * href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a
 * href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("leptonica")
public class Boxaa extends StructObject {
    static {
        BridJ.register();
    }

    /**
     * number of boxa in ptr array<br>
     * C type : l_int32
     */
    @Field(0)
    public int n() {
        return this.io.getIntField(this, 0);
    }

    /**
     * number of boxa in ptr array<br>
     * C type : l_int32
     */
    @Field(0)
    public Boxaa n(int n) {
        this.io.setIntField(this, 0, n);
        return this;
    }

    /**
     * number of boxa ptrs allocated<br>
     * C type : l_int32
     */
    @Field(1)
    public int nalloc() {
        return this.io.getIntField(this, 1);
    }

    /**
     * number of boxa ptrs allocated<br>
     * C type : l_int32
     */
    @Field(1)
    public Boxaa nalloc(int nalloc) {
        this.io.setIntField(this, 1, nalloc);
        return this;
    }

    /**
     * boxa ptr array<br>
     * C type : Boxa**
     */
    @Field(2)
    public Pointer<Pointer<Boxa>> boxa() {
        return this.io.getPointerField(this, 2);
    }

    /**
     * boxa ptr array<br>
     * C type : Boxa**
     */
    @Field(2)
    public Boxaa boxa(Pointer<Pointer<Boxa>> boxa) {
        this.io.setPointerField(this, 2, boxa);
        return this;
    }

    public Boxaa() {
        super();
    }

    public Boxaa(Pointer pointer) {
        super(pointer);
    }
}
