package de.vorb.leptonica;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * <i>native declaration :
 * C:\Users\Paul\Studium\Masterarbeit\Entwicklung\VS2013\
 * tesseract-vs2013\liblept\include\ccbord.h:101</i><br>
 * This file was autogenerated by <a
 * href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a
 * href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few
 * opensource projects.</a>.<br>
 * For help, please visit <a
 * href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a
 * href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("leptonica")
public class CCBorda extends StructObject {
    static {
        BridJ.register();
    }

    /**
     * input pix (may be null)<br>
     * C type : Pix*
     */
    @Field(0)
    public Pointer<Pix> pix() {
        return this.io.getPointerField(this, 0);
    }

    /**
     * input pix (may be null)<br>
     * C type : Pix*
     */
    @Field(0)
    public CCBorda pix(Pointer<Pix> pix) {
        this.io.setPointerField(this, 0, pix);
        return this;
    }

    /**
     * width of pix<br>
     * C type : l_int32
     */
    @Field(1)
    public int w() {
        return this.io.getIntField(this, 1);
    }

    /**
     * width of pix<br>
     * C type : l_int32
     */
    @Field(1)
    public CCBorda w(int w) {
        this.io.setIntField(this, 1, w);
        return this;
    }

    /**
     * height of pix<br>
     * C type : l_int32
     */
    @Field(2)
    public int h() {
        return this.io.getIntField(this, 2);
    }

    /**
     * height of pix<br>
     * C type : l_int32
     */
    @Field(2)
    public CCBorda h(int h) {
        this.io.setIntField(this, 2, h);
        return this;
    }

    /**
     * number of ccbord in ptr array<br>
     * C type : l_int32
     */
    @Field(3)
    public int n() {
        return this.io.getIntField(this, 3);
    }

    /**
     * number of ccbord in ptr array<br>
     * C type : l_int32
     */
    @Field(3)
    public CCBorda n(int n) {
        this.io.setIntField(this, 3, n);
        return this;
    }

    /**
     * number of ccbord ptrs allocated<br>
     * C type : l_int32
     */
    @Field(4)
    public int nalloc() {
        return this.io.getIntField(this, 4);
    }

    /**
     * number of ccbord ptrs allocated<br>
     * C type : l_int32
     */
    @Field(4)
    public CCBorda nalloc(int nalloc) {
        this.io.setIntField(this, 4, nalloc);
        return this;
    }

    /**
     * ccb ptr array<br>
     * C type : CCBord**
     */
    @Field(5)
    public Pointer<Pointer<CCBord>> ccb() {
        return this.io.getPointerField(this, 5);
    }

    /**
     * ccb ptr array<br>
     * C type : CCBord**
     */
    @Field(5)
    public CCBorda ccb(Pointer<Pointer<CCBord>> ccb) {
        this.io.setPointerField(this, 5, ccb);
        return this;
    }

    public CCBorda() {
        super();
    }

    public CCBorda(Pointer pointer) {
        super(pointer);
    }
}
