package de.vorb.leptonica;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : C:\Users\Paul\Studium\Masterarbeit\Entwicklung\VS2013\tesseract-vs2013\liblept\include\ccbord.h:86</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("leptonica") 
public class CCBord extends StructObject {
	static {
		BridJ.register();
	}
	/**
	 * component bitmap (min size)<br>
	 * C type : Pix*
	 */
	@Field(0) 
	public Pointer<Pix > pix() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * component bitmap (min size)<br>
	 * C type : Pix*
	 */
	@Field(0) 
	public CCBord pix(Pointer<Pix > pix) {
		this.io.setPointerField(this, 0, pix);
		return this;
	}
	/**
	 * regions of each closed curve<br>
	 * C type : Boxa*
	 */
	@Field(1) 
	public Pointer<Boxa > boxa() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * regions of each closed curve<br>
	 * C type : Boxa*
	 */
	@Field(1) 
	public CCBord boxa(Pointer<Boxa > boxa) {
		this.io.setPointerField(this, 1, boxa);
		return this;
	}
	/**
	 * initial border pixel locations<br>
	 * C type : Pta*
	 */
	@Field(2) 
	public Pointer<Pta > start() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * initial border pixel locations<br>
	 * C type : Pta*
	 */
	@Field(2) 
	public CCBord start(Pointer<Pta > start) {
		this.io.setPointerField(this, 2, start);
		return this;
	}
	/**
	 * number of handles; start at 1<br>
	 * C type : l_int32
	 */
	@Field(3) 
	public int refcount() {
		return this.io.getIntField(this, 3);
	}
	/**
	 * number of handles; start at 1<br>
	 * C type : l_int32
	 */
	@Field(3) 
	public CCBord refcount(int refcount) {
		this.io.setIntField(this, 3, refcount);
		return this;
	}
	/**
	 * ptaa of chain pixels (local)<br>
	 * C type : Ptaa*
	 */
	@Field(4) 
	public Pointer<Ptaa > local() {
		return this.io.getPointerField(this, 4);
	}
	/**
	 * ptaa of chain pixels (local)<br>
	 * C type : Ptaa*
	 */
	@Field(4) 
	public CCBord local(Pointer<Ptaa > local) {
		this.io.setPointerField(this, 4, local);
		return this;
	}
	/**
	 * ptaa of chain pixels (global)<br>
	 * C type : Ptaa*
	 */
	@Field(5) 
	public Pointer<Ptaa > global() {
		return this.io.getPointerField(this, 5);
	}
	/**
	 * ptaa of chain pixels (global)<br>
	 * C type : Ptaa*
	 */
	@Field(5) 
	public CCBord global(Pointer<Ptaa > global) {
		this.io.setPointerField(this, 5, global);
		return this;
	}
	/**
	 * numaa of chain code (step dir)<br>
	 * C type : Numaa*
	 */
	@Field(6) 
	public Pointer<Numaa > step() {
		return this.io.getPointerField(this, 6);
	}
	/**
	 * numaa of chain code (step dir)<br>
	 * C type : Numaa*
	 */
	@Field(6) 
	public CCBord step(Pointer<Numaa > step) {
		this.io.setPointerField(this, 6, step);
		return this;
	}
	/**
	 * pta of single chain (local)<br>
	 * C type : Pta*
	 */
	@Field(7) 
	public Pointer<Pta > splocal() {
		return this.io.getPointerField(this, 7);
	}
	/**
	 * pta of single chain (local)<br>
	 * C type : Pta*
	 */
	@Field(7) 
	public CCBord splocal(Pointer<Pta > splocal) {
		this.io.setPointerField(this, 7, splocal);
		return this;
	}
	/**
	 * pta of single chain (global)<br>
	 * C type : Pta*
	 */
	@Field(8) 
	public Pointer<Pta > spglobal() {
		return this.io.getPointerField(this, 8);
	}
	/**
	 * pta of single chain (global)<br>
	 * C type : Pta*
	 */
	@Field(8) 
	public CCBord spglobal(Pointer<Pta > spglobal) {
		this.io.setPointerField(this, 8, spglobal);
		return this;
	}
	public CCBord() {
		super();
	}
	public CCBord(Pointer pointer) {
		super(pointer);
	}
}
