package de.vorb.leptonica;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * CCBord contains:<br>
 * *    (1) a minimally-clipped bitmap of the component (pix),<br>
 *    (2) a boxa consisting of:<br>
 *          for the primary component:<br>
 *                (xul, yul) pixel location in global coords<br>
 *                (w, h) of the bitmap<br>
 *          for the hole components:<br>
 *                (x, y) in relative coordinates in primary component<br>
 *                (w, h) of the hole border (which is 2 pixels<br>
 *                       larger in each direction than the hole itself)<br>
 *    (3) a pta ('start') of the initial border pixel location for each<br>
 *        closed curve, all in relative coordinates of the primary<br>
 *        component.  This is given for the primary component,<br>
 *        followed by the hole components, if any.<br>
 *    (4) a refcount of the ccbord; used internally when a ccbord<br>
 *        is accessed from a ccborda (array of ccbord)<br>
 *    (5) a ptaa for the chain code for the border in relative<br>
 *        coordinates, where the first pta is the exterior border<br>
 *        and all other pta are for interior borders (holes)<br>
 *    (6) a ptaa for the global pixel loc rendition of the border,<br>
 *        where the first pta is the exterior border and all other<br>
 *        pta are for interior borders (holes).<br>
 *        This is derived from the local or step chain code.<br>
 *    (7) a numaa for the chain code for the border as orientation<br>
 *        directions between successive border pixels, where<br>
 *        the first numa is the exterior border and all other<br>
 *        numa are for interior borders (holes).  This is derived<br>
 *        from the local chain code.  The 8 directions are 0 - 7.<br>
 *    (8) a pta for a single chain for each c.c., comprised of outer<br>
 *        and hole borders, plus cut paths between them, all in<br>
 *        local coords.<br>
 *    (9) a pta for a single chain for each c.c., comprised of outer<br>
 *        and hole borders, plus cut paths between them, all in<br>
 *        global coords.<br>
 * <i>native declaration : C:\Users\Paul\Studium\Masterarbeit\Entwicklung\VS2013\tesseract-vs2013\liblept\include\ccbord.h:86</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CCBord extends Structure {
	/**
	 * component bitmap (min size)<br>
	 * C type : Pix*
	 */
	public de.vorb.leptonica.Pix.ByReference pix;
	/**
	 * regions of each closed curve<br>
	 * C type : Boxa*
	 */
	public de.vorb.leptonica.Boxa.ByReference boxa;
	/**
	 * initial border pixel locations<br>
	 * C type : Pta*
	 */
	public de.vorb.leptonica.Pta.ByReference start;
	/**
	 * number of handles; start at 1<br>
	 * C type : l_int32
	 */
	public int refcount;
	/**
	 * ptaa of chain pixels (local)<br>
	 * C type : Ptaa*
	 */
	public de.vorb.leptonica.Ptaa.ByReference local;
	/**
	 * ptaa of chain pixels (global)<br>
	 * C type : Ptaa*
	 */
	public de.vorb.leptonica.Ptaa.ByReference global;
	/**
	 * numaa of chain code (step dir)<br>
	 * C type : Numaa*
	 */
	public de.vorb.leptonica.Numaa.ByReference step;
	/**
	 * pta of single chain (local)<br>
	 * C type : Pta*
	 */
	public de.vorb.leptonica.Pta.ByReference splocal;
	/**
	 * pta of single chain (global)<br>
	 * C type : Pta*
	 */
	public de.vorb.leptonica.Pta.ByReference spglobal;
	public CCBord() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("pix", "boxa", "start", "refcount", "local", "global", "step", "splocal", "spglobal");
	}
	/**
	 * @param pix component bitmap (min size)<br>
	 * C type : Pix*<br>
	 * @param boxa regions of each closed curve<br>
	 * C type : Boxa*<br>
	 * @param start initial border pixel locations<br>
	 * C type : Pta*<br>
	 * @param refcount number of handles; start at 1<br>
	 * C type : l_int32<br>
	 * @param local ptaa of chain pixels (local)<br>
	 * C type : Ptaa*<br>
	 * @param global ptaa of chain pixels (global)<br>
	 * C type : Ptaa*<br>
	 * @param step numaa of chain code (step dir)<br>
	 * C type : Numaa*<br>
	 * @param splocal pta of single chain (local)<br>
	 * C type : Pta*<br>
	 * @param spglobal pta of single chain (global)<br>
	 * C type : Pta*
	 */
	public CCBord(de.vorb.leptonica.Pix.ByReference pix, de.vorb.leptonica.Boxa.ByReference boxa, de.vorb.leptonica.Pta.ByReference start, int refcount, de.vorb.leptonica.Ptaa.ByReference local, de.vorb.leptonica.Ptaa.ByReference global, de.vorb.leptonica.Numaa.ByReference step, de.vorb.leptonica.Pta.ByReference splocal, de.vorb.leptonica.Pta.ByReference spglobal) {
		super();
		this.pix = pix;
		this.boxa = boxa;
		this.start = start;
		this.refcount = refcount;
		this.local = local;
		this.global = global;
		this.step = step;
		this.splocal = splocal;
		this.spglobal = spglobal;
	}
	public static class ByReference extends CCBord implements Structure.ByReference {
		
	};
	public static class ByValue extends CCBord implements Structure.ByValue {
		
	};
}
