package de.vorb.leptonica;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * The JbData struct holds all the data required for<br>
 * the compressed jbig-type representation of a set of images.<br>
 * The data can be written to file, read back, and used<br>
 * to regenerate an approximate version of the original,<br>
 * which differs in two ways from the original:<br>
 *   (1) It uses a template image for each c.c. instead of the<br>
 *       original instance, for each occurrence on each page.<br>
 *   (2) It discards components with either a height or width larger<br>
 *       than the maximuma, given here by the lattice dimensions<br>
 *       used for storing the templates.<br>
 * <i>native declaration : C:\Users\Paul\Studium\Masterarbeit\Entwicklung\VS2013\tesseract-vs2013\liblept\include\jbclass.h:96</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class JbData extends Structure {
	/**
	 * template composite for all classes<br>
	 * C type : Pix*
	 */
	public de.vorb.leptonica.Pix.ByReference pix;
	/**
	 * number of pages<br>
	 * C type : l_int32
	 */
	public int npages;
	/**
	 * max width of original page images<br>
	 * C type : l_int32
	 */
	public int w;
	/**
	 * max height of original page images<br>
	 * C type : l_int32
	 */
	public int h;
	/**
	 * number of classes<br>
	 * C type : l_int32
	 */
	public int nclass;
	/**
	 * lattice width for template composite<br>
	 * C type : l_int32
	 */
	public int latticew;
	/**
	 * lattice height for template composite<br>
	 * C type : l_int32
	 */
	public int latticeh;
	/**
	 * array of class ids for each component<br>
	 * C type : Numa*
	 */
	public de.vorb.leptonica.Numa.ByReference naclass;
	/**
	 * array of page nums for each component<br>
	 * C type : Numa*
	 */
	public de.vorb.leptonica.Numa.ByReference napage;
	/**
	 * array of UL corners at which the<br>
	 * C type : Pta*
	 */
	public de.vorb.leptonica.Pta.ByReference ptaul;
	public JbData() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("pix", "npages", "w", "h", "nclass", "latticew", "latticeh", "naclass", "napage", "ptaul");
	}
	public static class ByReference extends JbData implements Structure.ByReference {
		
	};
	public static class ByValue extends JbData implements Structure.ByValue {
		
	};
}
