package de.vorb.leptonica;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
/**
 * <i>native declaration : C:\Users\Paul\Studium\Masterarbeit\Entwicklung\VS2013\tesseract-vs2013\liblept\include\array.h:137</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("leptonica") 
public class L_Bytea extends StructObject {
	static {
		BridJ.register();
	}
	/** number of bytes allocated in data array */
	@Ptr 
	@Field(0) 
	public long nalloc() {
		return this.io.getSizeTField(this, 0);
	}
	/** number of bytes allocated in data array */
	@Ptr 
	@Field(0) 
	public L_Bytea nalloc(long nalloc) {
		this.io.setSizeTField(this, 0, nalloc);
		return this;
	}
	/** number of bytes presently used */
	@Ptr 
	@Field(1) 
	public long size() {
		return this.io.getSizeTField(this, 1);
	}
	/** number of bytes presently used */
	@Ptr 
	@Field(1) 
	public L_Bytea size(long size) {
		this.io.setSizeTField(this, 1, size);
		return this;
	}
	/**
	 * reference count (1 if no clones)<br>
	 * C type : l_int32
	 */
	@Field(2) 
	public int refcount() {
		return this.io.getIntField(this, 2);
	}
	/**
	 * reference count (1 if no clones)<br>
	 * C type : l_int32
	 */
	@Field(2) 
	public L_Bytea refcount(int refcount) {
		this.io.setIntField(this, 2, refcount);
		return this;
	}
	/**
	 * data array<br>
	 * C type : l_uint8*
	 */
	@Field(3) 
	public Pointer<Byte > data() {
		return this.io.getPointerField(this, 3);
	}
	/**
	 * data array<br>
	 * C type : l_uint8*
	 */
	@Field(3) 
	public L_Bytea data(Pointer<Byte > data) {
		this.io.setPointerField(this, 3, data);
		return this;
	}
	public L_Bytea() {
		super();
	}
	public L_Bytea(Pointer pointer) {
		super(pointer);
	}
}
