package de.vorb.leptonica;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * <i>native declaration :
 * C:\Users\Paul\Studium\Masterarbeit\Entwicklung\VS2013\
 * tesseract-vs2013\liblept\include\array.h:114</i><br>
 * This file was autogenerated by <a
 * href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a
 * href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few
 * opensource projects.</a>.<br>
 * For help, please visit <a
 * href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a
 * href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("leptonica")
public class L_Dnaa extends StructObject {
    static {
        BridJ.register();
    }

    /**
     * size of allocated ptr array<br>
     * C type : l_int32
     */
    @Field(0)
    public int nalloc() {
        return this.io.getIntField(this, 0);
    }

    /**
     * size of allocated ptr array<br>
     * C type : l_int32
     */
    @Field(0)
    public L_Dnaa nalloc(int nalloc) {
        this.io.setIntField(this, 0, nalloc);
        return this;
    }

    /**
     * number of L_Dna saved<br>
     * C type : l_int32
     */
    @Field(1)
    public int n() {
        return this.io.getIntField(this, 1);
    }

    /**
     * number of L_Dna saved<br>
     * C type : l_int32
     */
    @Field(1)
    public L_Dnaa n(int n) {
        this.io.setIntField(this, 1, n);
        return this;
    }

    /**
     * array of L_Dna<br>
     * C type : L_Dna**
     */
    @Field(2)
    public Pointer<Pointer<L_Dna>> dna() {
        return this.io.getPointerField(this, 2);
    }

    /**
     * array of L_Dna<br>
     * C type : L_Dna**
     */
    @Field(2)
    public L_Dnaa dna(Pointer<Pointer<L_Dna>> dna) {
        this.io.setPointerField(this, 2, dna);
        return this;
    }

    public L_Dnaa() {
        super();
    }

    public L_Dnaa(Pointer pointer) {
        super(pointer);
    }
}
