package de.vorb.leptonica;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : C:\Users\Paul\Studium\Masterarbeit\Entwicklung\VS2013\tesseract-vs2013\liblept\include\ptra.h:58</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("leptonica") 
public class L_Ptraa extends StructObject {
	static {
		BridJ.register();
	}
	/**
	 * size of allocated ptr array<br>
	 * C type : l_int32
	 */
	@Field(0) 
	public int nalloc() {
		return this.io.getIntField(this, 0);
	}
	/**
	 * size of allocated ptr array<br>
	 * C type : l_int32
	 */
	@Field(0) 
	public L_Ptraa nalloc(int nalloc) {
		this.io.setIntField(this, 0, nalloc);
		return this;
	}
	/**
	 * array of ptra<br>
	 * C type : L_Ptra**
	 */
	@Field(1) 
	public Pointer<Pointer<L_Ptra > > ptra() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * array of ptra<br>
	 * C type : L_Ptra**
	 */
	@Field(1) 
	public L_Ptraa ptra(Pointer<Pointer<L_Ptra > > ptra) {
		this.io.setPointerField(this, 1, ptra);
		return this;
	}
	public L_Ptraa() {
		super();
	}
	public L_Ptraa(Pointer pointer) {
		super(pointer);
	}
}
