package de.vorb.leptonica;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * <i>native declaration :
 * C:\Users\Paul\Studium\Masterarbeit\Entwicklung\VS2013\
 * tesseract-vs2013\liblept\include\stack.h:55</i><br>
 * This file was autogenerated by <a
 * href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a
 * href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few
 * opensource projects.</a>.<br>
 * For help, please visit <a
 * href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a
 * href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("leptonica")
public class L_Stack extends StructObject {
    static {
        BridJ.register();
    }

    /**
     * size of ptr array<br>
     * C type : l_int32
     */
    @Field(0)
    public int nalloc() {
        return this.io.getIntField(this, 0);
    }

    /**
     * size of ptr array<br>
     * C type : l_int32
     */
    @Field(0)
    public L_Stack nalloc(int nalloc) {
        this.io.setIntField(this, 0, nalloc);
        return this;
    }

    /**
     * number of stored elements<br>
     * C type : l_int32
     */
    @Field(1)
    public int n() {
        return this.io.getIntField(this, 1);
    }

    /**
     * number of stored elements<br>
     * C type : l_int32
     */
    @Field(1)
    public L_Stack n(int n) {
        this.io.setIntField(this, 1, n);
        return this;
    }

    /**
     * ptr array<br>
     * C type : void**
     */
    @Field(2)
    public Pointer<Pointer<?>> array() {
        return this.io.getPointerField(this, 2);
    }

    /**
     * ptr array<br>
     * C type : void**
     */
    @Field(2)
    public L_Stack array(Pointer<Pointer<?>> array) {
        this.io.setPointerField(this, 2, array);
        return this;
    }

    /**
     * auxiliary stack<br>
     * C type : L_Stack*
     */
    @Field(3)
    public Pointer<L_Stack> auxstack() {
        return this.io.getPointerField(this, 3);
    }

    /**
     * auxiliary stack<br>
     * C type : L_Stack*
     */
    @Field(3)
    public L_Stack auxstack(Pointer<L_Stack> auxstack) {
        this.io.setPointerField(this, 3, auxstack);
        return this;
    }

    public L_Stack() {
        super();
    }

    public L_Stack(Pointer pointer) {
        super(pointer);
    }
}
