package de.vorb.leptonica;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * <i>native declaration :
 * C:\Users\Paul\Studium\Masterarbeit\Entwicklung\VS2013\
 * tesseract-vs2013\liblept\include\array.h:89</i><br>
 * This file was autogenerated by <a
 * href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a
 * href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few
 * opensource projects.</a>.<br>
 * For help, please visit <a
 * href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a
 * href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("leptonica")
public class NumaHash extends StructObject {
    static {
        BridJ.register();
    }

    /** C type : l_int32 */
    @Field(0)
    public int nbuckets() {
        return this.io.getIntField(this, 0);
    }

    /** C type : l_int32 */
    @Field(0)
    public NumaHash nbuckets(int nbuckets) {
        this.io.setIntField(this, 0, nbuckets);
        return this;
    }

    /**
     * initial size of each numa that is made<br>
     * C type : l_int32
     */
    @Field(1)
    public int initsize() {
        return this.io.getIntField(this, 1);
    }

    /**
     * initial size of each numa that is made<br>
     * C type : l_int32
     */
    @Field(1)
    public NumaHash initsize(int initsize) {
        this.io.setIntField(this, 1, initsize);
        return this;
    }

    /** C type : Numa** */
    @Field(2)
    public Pointer<Pointer<Numa>> numa() {
        return this.io.getPointerField(this, 2);
    }

    /** C type : Numa** */
    @Field(2)
    public NumaHash numa(Pointer<Pointer<Numa>> numa) {
        this.io.setPointerField(this, 2, numa);
        return this;
    }

    public NumaHash() {
        super();
    }

    public NumaHash(Pointer pointer) {
        super(pointer);
    }
}
