package de.vorb.leptonica;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : C:\Users\Paul\Studium\Masterarbeit\Entwicklung\VS2013\tesseract-vs2013\liblept\include\array.h:68</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("leptonica") 
public class Numaa extends StructObject {
	static {
		BridJ.register();
	}
	/**
	 * size of allocated ptr array<br>
	 * C type : l_int32
	 */
	@Field(0) 
	public int nalloc() {
		return this.io.getIntField(this, 0);
	}
	/**
	 * size of allocated ptr array<br>
	 * C type : l_int32
	 */
	@Field(0) 
	public Numaa nalloc(int nalloc) {
		this.io.setIntField(this, 0, nalloc);
		return this;
	}
	/**
	 * number of Numa saved<br>
	 * C type : l_int32
	 */
	@Field(1) 
	public int n() {
		return this.io.getIntField(this, 1);
	}
	/**
	 * number of Numa saved<br>
	 * C type : l_int32
	 */
	@Field(1) 
	public Numaa n(int n) {
		this.io.setIntField(this, 1, n);
		return this;
	}
	/**
	 * array of Numa<br>
	 * C type : Numa**
	 */
	@Field(2) 
	public Pointer<Pointer<Numa > > numa() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * array of Numa<br>
	 * C type : Numa**
	 */
	@Field(2) 
	public Numaa numa(Pointer<Pointer<Numa > > numa) {
		this.io.setPointerField(this, 2, numa);
		return this;
	}
	public Numaa() {
		super();
	}
	public Numaa(Pointer pointer) {
		super(pointer);
	}
}
