package de.vorb.leptonica;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * Array of number arrays<br>
 * <i>native declaration : C:\Users\Paul\Studium\Masterarbeit\Entwicklung\VS2013\tesseract-vs2013\liblept\include\array.h:68</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class Numaa extends Structure {
	/**
	 * size of allocated ptr array<br>
	 * C type : l_int32
	 */
	public int nalloc;
	/**
	 * number of Numa saved<br>
	 * C type : l_int32
	 */
	public int n;
	/**
	 * array of Numa<br>
	 * C type : Numa**
	 */
	public de.vorb.leptonica.Numa.ByReference[] numa;
	public Numaa() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("nalloc", "n", "numa");
	}
	/**
	 * @param nalloc size of allocated ptr array<br>
	 * C type : l_int32<br>
	 * @param n number of Numa saved<br>
	 * C type : l_int32<br>
	 * @param numa array of Numa<br>
	 * C type : Numa**
	 */
	public Numaa(int nalloc, int n, de.vorb.leptonica.Numa.ByReference numa[]) {
		super();
		this.nalloc = nalloc;
		this.n = n;
		if ((numa.length != this.numa.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.numa = numa;
	}
	public static class ByReference extends Numaa implements Structure.ByReference {
		
	};
	public static class ByValue extends Numaa implements Structure.ByValue {
		
	};
}
