package de.vorb.leptonica;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * -------------------------------------------------------------------------*<br>
 *                     PixaComp: array of compressed pix                   *<br>
 * -------------------------------------------------------------------------<br>
 * <i>native declaration : C:\Users\Paul\Studium\Masterarbeit\Entwicklung\VS2013\tesseract-vs2013\liblept\include\pix.h:594</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("leptonica") 
public class PixaComp extends StructObject {
	static {
		BridJ.register();
	}
	/**
	 * number of PixComp in ptr array<br>
	 * C type : l_int32
	 */
	@Field(0) 
	public int n() {
		return this.io.getIntField(this, 0);
	}
	/**
	 * number of PixComp in ptr array<br>
	 * C type : l_int32
	 */
	@Field(0) 
	public PixaComp n(int n) {
		this.io.setIntField(this, 0, n);
		return this;
	}
	/**
	 * number of PixComp ptrs allocated<br>
	 * C type : l_int32
	 */
	@Field(1) 
	public int nalloc() {
		return this.io.getIntField(this, 1);
	}
	/**
	 * number of PixComp ptrs allocated<br>
	 * C type : l_int32
	 */
	@Field(1) 
	public PixaComp nalloc(int nalloc) {
		this.io.setIntField(this, 1, nalloc);
		return this;
	}
	/**
	 * indexing offset into ptr array<br>
	 * C type : l_int32
	 */
	@Field(2) 
	public int offset() {
		return this.io.getIntField(this, 2);
	}
	/**
	 * indexing offset into ptr array<br>
	 * C type : l_int32
	 */
	@Field(2) 
	public PixaComp offset(int offset) {
		this.io.setIntField(this, 2, offset);
		return this;
	}
	/**
	 * the array of ptrs to PixComp<br>
	 * C type : PixComp**
	 */
	@Field(3) 
	public Pointer<Pointer<PixComp > > pixc() {
		return this.io.getPointerField(this, 3);
	}
	/**
	 * the array of ptrs to PixComp<br>
	 * C type : PixComp**
	 */
	@Field(3) 
	public PixaComp pixc(Pointer<Pointer<PixComp > > pixc) {
		this.io.setPointerField(this, 3, pixc);
		return this;
	}
	/**
	 * array of boxes<br>
	 * C type : Boxa*
	 */
	@Field(4) 
	public Pointer<Boxa > boxa() {
		return this.io.getPointerField(this, 4);
	}
	/**
	 * array of boxes<br>
	 * C type : Boxa*
	 */
	@Field(4) 
	public PixaComp boxa(Pointer<Boxa > boxa) {
		this.io.setPointerField(this, 4, boxa);
		return this;
	}
	public PixaComp() {
		super();
	}
	public PixaComp(Pointer pointer) {
		super(pointer);
	}
}
