package de.vorb.leptonica;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : C:\Users\Paul\Studium\Masterarbeit\Entwicklung\VS2013\tesseract-vs2013\liblept\include\pix.h:417</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class Pixaa extends Structure {
	/**
	 * number of Pixa in ptr array<br>
	 * C type : l_int32
	 */
	public int n;
	/**
	 * number of Pixa ptrs allocated<br>
	 * C type : l_int32
	 */
	public int nalloc;
	/**
	 * array of ptrs to pixa<br>
	 * C type : Pixa**
	 */
	public de.vorb.leptonica.Pixa.ByReference[] pixa;
	/**
	 * array of boxes<br>
	 * C type : Boxa*
	 */
	public de.vorb.leptonica.Boxa.ByReference boxa;
	public Pixaa() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("n", "nalloc", "pixa", "boxa");
	}
	/**
	 * @param n number of Pixa in ptr array<br>
	 * C type : l_int32<br>
	 * @param nalloc number of Pixa ptrs allocated<br>
	 * C type : l_int32<br>
	 * @param pixa array of ptrs to pixa<br>
	 * C type : Pixa**<br>
	 * @param boxa array of boxes<br>
	 * C type : Boxa*
	 */
	public Pixaa(int n, int nalloc, de.vorb.leptonica.Pixa.ByReference pixa[], de.vorb.leptonica.Boxa.ByReference boxa) {
		super();
		this.n = n;
		this.nalloc = nalloc;
		if ((pixa.length != this.pixa.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.pixa = pixa;
		this.boxa = boxa;
	}
	public static class ByReference extends Pixaa implements Structure.ByReference {
		
	};
	public static class ByValue extends Pixaa implements Structure.ByValue {
		
	};
}
