package de.vorb.leptonica;
import com.ochafik.lang.jnaerator.runtime.NativeSize;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * -------------------------------------------------------------------------*<br>
 *                        PixComp: compressed pix                          *<br>
 * -------------------------------------------------------------------------<br>
 * <i>native declaration : C:\Users\Paul\Studium\Masterarbeit\Entwicklung\VS2013\tesseract-vs2013\liblept\include\pix.h:570</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PixComp extends Structure {
	/**
	 * width in pixels<br>
	 * C type : l_int32
	 */
	public int w;
	/**
	 * height in pixels<br>
	 * C type : l_int32
	 */
	public int h;
	/**
	 * depth in bits<br>
	 * C type : l_int32
	 */
	public int d;
	/**
	 * image res (ppi) in x direction<br>
	 * C type : l_int32
	 */
	public int xres;
	/**
	 * (use 0 if unknown)<br>
	 * image res (ppi) in y direction<br>
	 * C type : l_int32
	 */
	public int yres;
	/**
	 * (use 0 if unknown)<br>
	 * compressed format (IFF_TIFF_G4,<br>
	 * C type : l_int32
	 */
	public int comptype;
	/**
	 * IFF_PNG, IFF_JFIF_JPEG)<br>
	 * text string associated with pix<br>
	 * C type : char*
	 */
	public Pointer text;
	/**
	 * flag (1 for cmap, 0 otherwise)<br>
	 * C type : l_int32
	 */
	public int cmapflag;
	/**
	 * the compressed image data<br>
	 * C type : l_uint8*
	 */
	public Pointer data;
	/** size of the data array */
	public NativeSize size;
	public PixComp() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("w", "h", "d", "xres", "yres", "comptype", "text", "cmapflag", "data", "size");
	}
	public static class ByReference extends PixComp implements Structure.ByReference {
		
	};
	public static class ByValue extends PixComp implements Structure.ByValue {
		
	};
}
