package de.vorb.leptonica;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * <i>native declaration :
 * C:\Users\Paul\Studium\Masterarbeit\Entwicklung\VS2013\
 * tesseract-vs2013\liblept\include\pix.h:138</i><br>
 * This file was autogenerated by <a
 * href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a
 * href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few
 * opensource projects.</a>.<br>
 * For help, please visit <a
 * href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a
 * href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("leptonica")
public class PixColormap extends StructObject {
    static {
        BridJ.register();
    }

    /**
     * colormap table (array of RGBA_QUAD)<br>
     * C type : void*
     */
    @Field(0)
    public Pointer<?> array() {
        return this.io.getPointerField(this, 0);
    }

    /**
     * colormap table (array of RGBA_QUAD)<br>
     * C type : void*
     */
    @Field(0)
    public PixColormap array(Pointer<?> array) {
        this.io.setPointerField(this, 0, array);
        return this;
    }

    /**
     * of pix (1, 2, 4 or 8 bpp)<br>
     * C type : l_int32
     */
    @Field(1)
    public int depth() {
        return this.io.getIntField(this, 1);
    }

    /**
     * of pix (1, 2, 4 or 8 bpp)<br>
     * C type : l_int32
     */
    @Field(1)
    public PixColormap depth(int depth) {
        this.io.setIntField(this, 1, depth);
        return this;
    }

    /**
     * number of color entries allocated<br>
     * C type : l_int32
     */
    @Field(2)
    public int nalloc() {
        return this.io.getIntField(this, 2);
    }

    /**
     * number of color entries allocated<br>
     * C type : l_int32
     */
    @Field(2)
    public PixColormap nalloc(int nalloc) {
        this.io.setIntField(this, 2, nalloc);
        return this;
    }

    /**
     * number of color entries used<br>
     * C type : l_int32
     */
    @Field(3)
    public int n() {
        return this.io.getIntField(this, 3);
    }

    /**
     * number of color entries used<br>
     * C type : l_int32
     */
    @Field(3)
    public PixColormap n(int n) {
        this.io.setIntField(this, 3, n);
        return this;
    }

    public PixColormap() {
        super();
    }

    public PixColormap(Pointer pointer) {
        super(pointer);
    }
}
