package de.vorb.leptonica;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * -------------------------------------------------------------------------*<br>
 *                              Array of Pta                               *<br>
 * -------------------------------------------------------------------------<br>
 * <i>native declaration : C:\Users\Paul\Studium\Masterarbeit\Entwicklung\VS2013\tesseract-vs2013\liblept\include\pix.h:477</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("leptonica") 
public class Ptaa extends StructObject {
	static {
		BridJ.register();
	}
	/**
	 * number of pta in ptr array<br>
	 * C type : l_int32
	 */
	@Field(0) 
	public int n() {
		return this.io.getIntField(this, 0);
	}
	/**
	 * number of pta in ptr array<br>
	 * C type : l_int32
	 */
	@Field(0) 
	public Ptaa n(int n) {
		this.io.setIntField(this, 0, n);
		return this;
	}
	/**
	 * number of pta ptrs allocated<br>
	 * C type : l_int32
	 */
	@Field(1) 
	public int nalloc() {
		return this.io.getIntField(this, 1);
	}
	/**
	 * number of pta ptrs allocated<br>
	 * C type : l_int32
	 */
	@Field(1) 
	public Ptaa nalloc(int nalloc) {
		this.io.setIntField(this, 1, nalloc);
		return this;
	}
	/**
	 * pta ptr array<br>
	 * C type : Pta**
	 */
	@Field(2) 
	public Pointer<Pointer<Pta > > pta() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * pta ptr array<br>
	 * C type : Pta**
	 */
	@Field(2) 
	public Ptaa pta(Pointer<Pointer<Pta > > pta) {
		this.io.setPointerField(this, 2, pta);
		return this;
	}
	public Ptaa() {
		super();
	}
	public Ptaa(Pointer pointer) {
		super(pointer);
	}
}
