package de.vorb.leptonica;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * <i>native declaration :
 * C:\Users\Paul\Studium\Masterarbeit\Entwicklung\VS2013\
 * tesseract-vs2013\liblept\include\array.h:126</i><br>
 * This file was autogenerated by <a
 * href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a
 * href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few
 * opensource projects.</a>.<br>
 * For help, please visit <a
 * href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a
 * href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("leptonica")
public class Sarray extends StructObject {
    static {
        BridJ.register();
    }

    /**
     * size of allocated ptr array<br>
     * C type : l_int32
     */
    @Field(0)
    public int nalloc() {
        return this.io.getIntField(this, 0);
    }

    /**
     * size of allocated ptr array<br>
     * C type : l_int32
     */
    @Field(0)
    public Sarray nalloc(int nalloc) {
        this.io.setIntField(this, 0, nalloc);
        return this;
    }

    /**
     * number of strings allocated<br>
     * C type : l_int32
     */
    @Field(1)
    public int n() {
        return this.io.getIntField(this, 1);
    }

    /**
     * number of strings allocated<br>
     * C type : l_int32
     */
    @Field(1)
    public Sarray n(int n) {
        this.io.setIntField(this, 1, n);
        return this;
    }

    /**
     * reference count (1 if no clones)<br>
     * C type : l_int32
     */
    @Field(2)
    public int refcount() {
        return this.io.getIntField(this, 2);
    }

    /**
     * reference count (1 if no clones)<br>
     * C type : l_int32
     */
    @Field(2)
    public Sarray refcount(int refcount) {
        this.io.setIntField(this, 2, refcount);
        return this;
    }

    /**
     * string array<br>
     * C type : char**
     */
    @Field(3)
    public Pointer<Pointer<Byte>> array() {
        return this.io.getPointerField(this, 3);
    }

    /**
     * string array<br>
     * C type : char**
     */
    @Field(3)
    public Sarray array(Pointer<Pointer<Byte>> array) {
        this.io.setPointerField(this, 3, array);
        return this;
    }

    public Sarray() {
        super();
    }

    public Sarray(Pointer pointer) {
        super(pointer);
    }
}
