package de.vorb.leptonica;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * -------------------------------------------------------------------------*<br>
 * Sel and Sel array *<br>
 * -------------------------------------------------------------------------<br>
 * <i>native declaration :
 * C:\Users\Paul\Studium\Masterarbeit\Entwicklung\VS2013\
 * tesseract-vs2013\liblept\include\morph.h:59</i><br>
 * This file was autogenerated by <a
 * href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a
 * href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few
 * opensource projects.</a>.<br>
 * For help, please visit <a
 * href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a
 * href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("leptonica")
public class Sel extends StructObject {
    static {
        BridJ.register();
    }

    /**
     * sel height<br>
     * C type : l_int32
     */
    @Field(0)
    public int sy() {
        return this.io.getIntField(this, 0);
    }

    /**
     * sel height<br>
     * C type : l_int32
     */
    @Field(0)
    public Sel sy(int sy) {
        this.io.setIntField(this, 0, sy);
        return this;
    }

    /**
     * sel width<br>
     * C type : l_int32
     */
    @Field(1)
    public int sx() {
        return this.io.getIntField(this, 1);
    }

    /**
     * sel width<br>
     * C type : l_int32
     */
    @Field(1)
    public Sel sx(int sx) {
        this.io.setIntField(this, 1, sx);
        return this;
    }

    /**
     * y location of sel origin<br>
     * C type : l_int32
     */
    @Field(2)
    public int cy() {
        return this.io.getIntField(this, 2);
    }

    /**
     * y location of sel origin<br>
     * C type : l_int32
     */
    @Field(2)
    public Sel cy(int cy) {
        this.io.setIntField(this, 2, cy);
        return this;
    }

    /**
     * x location of sel origin<br>
     * C type : l_int32
     */
    @Field(3)
    public int cx() {
        return this.io.getIntField(this, 3);
    }

    /**
     * x location of sel origin<br>
     * C type : l_int32
     */
    @Field(3)
    public Sel cx(int cx) {
        this.io.setIntField(this, 3, cx);
        return this;
    }

    /**
     * {0,1,2}; data[i][j] in [row][col] order<br>
     * C type : l_int32**
     */
    @Field(4)
    public Pointer<Pointer<Integer>> data() {
        return this.io.getPointerField(this, 4);
    }

    /**
     * {0,1,2}; data[i][j] in [row][col] order<br>
     * C type : l_int32**
     */
    @Field(4)
    public Sel data(Pointer<Pointer<Integer>> data) {
        this.io.setPointerField(this, 4, data);
        return this;
    }

    /**
     * used to find sel by name<br>
     * C type : char*
     */
    @Field(5)
    public Pointer<Byte> name() {
        return this.io.getPointerField(this, 5);
    }

    /**
     * used to find sel by name<br>
     * C type : char*
     */
    @Field(5)
    public Sel name(Pointer<Byte> name) {
        this.io.setPointerField(this, 5, name);
        return this;
    }

    public Sel() {
        super();
    }

    public Sel(Pointer pointer) {
        super(pointer);
    }
}
