package de.vorb.leptonica;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : C:\Users\Paul\Studium\Masterarbeit\Entwicklung\VS2013\tesseract-vs2013\liblept\include\morph.h:70</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("leptonica") 
public class Sela extends StructObject {
	static {
		BridJ.register();
	}
	/**
	 * number of sel actually stored<br>
	 * C type : l_int32
	 */
	@Field(0) 
	public int n() {
		return this.io.getIntField(this, 0);
	}
	/**
	 * number of sel actually stored<br>
	 * C type : l_int32
	 */
	@Field(0) 
	public Sela n(int n) {
		this.io.setIntField(this, 0, n);
		return this;
	}
	/**
	 * size of allocated ptr array<br>
	 * C type : l_int32
	 */
	@Field(1) 
	public int nalloc() {
		return this.io.getIntField(this, 1);
	}
	/**
	 * size of allocated ptr array<br>
	 * C type : l_int32
	 */
	@Field(1) 
	public Sela nalloc(int nalloc) {
		this.io.setIntField(this, 1, nalloc);
		return this;
	}
	/**
	 * sel ptr array<br>
	 * C type : Sel**
	 */
	@Field(2) 
	public Pointer<Pointer<Sel > > sel() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * sel ptr array<br>
	 * C type : Sel**
	 */
	@Field(2) 
	public Sela sel(Pointer<Pointer<Sel > > sel) {
		this.io.setPointerField(this, 2, sel);
		return this;
	}
	public Sela() {
		super();
	}
	public Sela(Pointer pointer) {
		super(pointer);
	}
}
